{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "# insert at 1, 0 is the script path (or '' in REPL)\n",
    "sys.path.insert(0, 'C:/Users/Admin/Desktop/Antiscience/code')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Как известно, наш мир - это компьютерная симуляция, написанная много лет назад начинающей командой разработчиков. В коде этой программы по-прежнему находят многочисленные баги. Некоторые из них настолько серьезные, что пофиксить их пока не удалось никому.** \n",
    "\n",
    "**Так например иногда разработчики находят недочеты в системе взаимодействия между пользователями. И который раз уже работу над этими вопросами поручают Лупе и Пупе в надежде на то, что они смогут сделать все нормально... Вот и недавно на тестовом сервере они должны были выпустить пробную версию ивента, в котором нужно избегать других пользователей. Но на проде все перепутали, и Лупа получил задание за Пупу, а Пупа залил все на глобальный сервер...**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import world"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Создание континентов: 100%|████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 7015.56it/s]\n",
      "Создание городов: 100%|█████████████████████████████████████████████████| 2700000/2700000 [00:01<00:00, 1994605.98it/s]\n",
      "Обновление базы данных пользователей:   0%|                                                      | 0/8 [00:00<?, ?it/s]\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Ошибка обновления базы данных",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-3-2700bc1a9efd>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mworld\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcreate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mC:/Users/Admin/Desktop/Antiscience/code\\world.py\u001b[0m in \u001b[0;36mcreate\u001b[1;34m()\u001b[0m\n\u001b[0;32m      8\u001b[0m     \u001b[1;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mtqdm\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0marange\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m7.5\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdesc\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'Обновление базы данных пользователей'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      9\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mi\u001b[0m \u001b[1;33m<=\u001b[0m \u001b[1;36m5\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 10\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Ошибка обновления базы данных'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m: Ошибка обновления базы данных"
     ]
    }
   ],
   "source": [
    "world.create()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Результаты такого косяка не заставили себя ждать. Довольно скоро стали поступать многочисленные запросы от пользователей содержания:**\n",
    "\n",
    "\"Перезапустите год!!! у меня вирус...\" и \"SMTH ELSE\"\n",
    "\n",
    "**Увы, простые советы перезапустить программу были отвергнуты пользователями в штыки. Поэтому остальной части команды разработчиков как всегда пришлось отдуваться за Лупу и Пупу и в срочном порядке выпускать патч для стабилизации ситуации.**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Добавить мемные картиночки для каждого из пунктов !!!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Патч №1.4.8.8 версия 80dol(lar) от 15.03, кодовое название \"Самоизоляция\"\n",
    "Список фиксов:\n",
    "\n",
    "* Ограничен доступ к локации \"Улица\": в этой версии патча она доступна только в случае необходимости доступа к зонам \"Ближайший магазин\", \"Ближайшая аптека\" и \"Работа\", а также при наличии NPC \"Собака\".\n",
    "\n",
    "* Все локации, в которые можно попасть через зону \"Улица\", заблокированы на неопределенный срок. При попытке попасть в запрещенную зону будет высвечиваться информационное окно с сообщением **\"Эта зона еще не разблокирована.\"**, возможно появление NPC \"Полиция\" и включение модуля \"Штрафы\".\n",
    "\n",
    "* Добавлена опция ношения защиты типа \"Маска\" в локациях, доступных различным пользователям.\n",
    "\n",
    "* Была добавлены инструменты \"Удаленное общение\" и \"Дистанционная работа/обучение\" # **картинка \"УдАленка\"** #. На момент выпуска патча эти опции не до конца отлажены, следите за обновлениями.\n",
    "\n",
    "* Были пополнены запасы ресурсов \"Туалетная бумага\" и \"Гречка\" части пользователей.\n",
    "\n",
    "UPD от 15.04:\n",
    "\n",
    "* Для использования инструментов \"Автомобиль\" и \"Велосипед\" пользователям нужно указать цель их использования в соответствующем окне, всплывающем при попытке их использования."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Опрос пользователей???"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
